import pandas as pd
import numpy as np


def generate_solar_panel_data(dataframe : dict, parameters: dict = {"rated_power": 1}):
    """
    Generate solar panel data for 24 hours with 1 hour intervals.
    
    Parameters
    ----------
    dataframe : dict
        Dictionary of dataframes for irradiation data. We assume that the two colums are "date" and "direct_irradiation".
    parameters : dict, optional
        Dictionary with rated power. The default is {"rated_power": 1}.
    
    Returns
    -------
    pd.DataFrame
        Dataframe with solar panel data.
    """
    irradation_df = dataframe["solar_irradation"]
    # add column for the rated power and calculate the energy generated by irradation * rated power
    irradation_df["energy_generated"] = irradation_df["direct_irradiation"] * parameters["rated_power"]
    # drop direct_irradiation column
    irradation_df.drop(columns=["direct_irradiation"], inplace=True)
    
    return irradation_df

# example usage
if __name__ == "__main__":
    parameters = {"rated_power": 10}  # rated power of the solar panel
    # generate a dataframe with date and direct_irradiation columns
    irradation_df = pd.DataFrame()
    irradation_df["date"] = pd.date_range(start = pd.Timestamp.now(), periods = 24, freq = "H")
    irradation_df["direct_irradiation"] = np.random.rand(24)
    dataframe = {"solar_irradation": irradation_df}
    
    solar_panel_data = generate_solar_panel_data(dataframe=dataframe, parameters=parameters)
    print(solar_panel_data)