import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import openmeteo_wind

def generate_wind_turbine_data(dataframe: dict, parameters: dict = {"rated_power": 1, "cut_in_speed": 3.5, "rated_speed" : 14, "cut_out_speed": 25}):
    """
    Generate wind turbine data for 24 hours with 1 hour intervals.
    Parameters
    ----------
    dataframe : dict
        Dictionary of dataframes for wind data. We assume that the two colums are "date" and "wind_speed_10m".
    parameters : dict
        Dictionary with rated power, cut in speed, rated speed and cut out speed. The default is {"rated_power": 1, "cut_in_speed": 3.5, "rated_speed" : 14, "cut_out_speed": 25}.
    Returns
    -------
    pd.DataFrame
        Dataframe with wind turbine data.
    """
    wind_df = dataframe["wind_data"]
    # add column for the rated power and calculate the energy generated by wind speed
    wind_df["energy_generated"] = np.where(
        wind_df["wind_speed_10m"] < parameters["cut_in_speed"], 0,
        np.where(
            wind_df["wind_speed_10m"] > parameters["cut_out_speed"], 0,
            np.where(
                wind_df["wind_speed_10m"] < parameters["rated_speed"],
                ((wind_df["wind_speed_10m"] - parameters["cut_in_speed"]) / (parameters["rated_speed"] - parameters["cut_in_speed"]))**3 * parameters["rated_power"],
                parameters["rated_power"]
            )
        )
    )
    # drop wind_speed_10m column
    # wind_df.drop(columns=["wind_speed_10m"], inplace=True)
    
    return wind_df
# example usage
if __name__ == "__main__":
    parameters = {"rated_power": 10, "cut_in_speed": 3.5, "rated_speed" : 14, "cut_out_speed": 25}  # rated power of the wind turbine
    # generate a dataframe with date and wind_speed_10m columns
    # wind_df = pd.DataFrame()
    # wind_df["date"] = pd.date_range(start = pd.Timestamp.now(), periods = 24, freq = "H")
    # ## increase the wind speed by 1 m/s every hour
    # wind_df["wind_speed_10m"] = np.arange(0, 48, 2)
    
    # dataframe = {"wind_data": wind_df}
    
    parameters1 = {"latitude": 57.0488, "longitude": 9.9217}  # Aalborg, Denmark
    wind_turbine_data = openmeteo_wind.get_wind_data(parameters=parameters1)
    wind_power = generate_wind_turbine_data(dataframe={"wind_data": wind_turbine_data}, parameters=parameters)
    print(wind_turbine_data)
    # graph the data
    plt.plot(wind_turbine_data["date"], wind_turbine_data["energy_generated"])
    plt.xlabel("Date")
    plt.ylabel("Energy generated")
    plt.title("Wind turbine data")
    plt.show()